#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Fri Jan 14 01:21:12 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainWindow.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_3 = wx.Panel(self.notebook, -1)
        self.notebook_1_pane_2 = wx.Panel(self.notebook, -1)
        self.notebook_1_pane_1 = wx.Panel(self.notebook, -1)
        self.label_1 = wx.StaticText(self.notebook_1_pane_1, -1, "Status:")
        self.status = wx.StaticText(self.notebook_1_pane_1, -1, "Not Connected")
        self.label_3 = wx.StaticText(self.notebook_1_pane_1, -1, "Default Temperature:")
        self.default_temperature = wx.SpinCtrl(self.notebook_1_pane_1, -1, "10", min=10, max=30)
        self.label_4 = wx.StaticText(self.notebook_1_pane_1, -1, "Current Temperature:")
        self.temperature = wx.StaticText(self.notebook_1_pane_1, -1, "10")
        self.bitmap_1 = wx.StaticBitmap(self.notebook_1_pane_1, -1, wx.Bitmap("./ui/logo.png", wx.BITMAP_TYPE_ANY))
        self.programme_editor = wx.TextCtrl(self.notebook_1_pane_2, -1, "", style=wx.TE_MULTILINE)
        self.button_3 = wx.Button(self.notebook_1_pane_2, -1, "Help")
        self.reset_changes_btn = wx.Button(self.notebook_1_pane_2, -1, "Reset Changes")
        self.load_programmes_btn = wx.Button(self.notebook_1_pane_2, -1, "Load Programmes")
        self.label_5 = wx.StaticText(self.notebook_1_pane_3, -1, "Time and Date:")
        self.device_time_date = wx.StaticText(self.notebook_1_pane_3, -1, "01/01/2011 05:30:20")
        self.label_6 = wx.StaticText(self.notebook_1_pane_3, -1, "(Date Code: +3, Mon)")
        self.refresh_time_btn = wx.Button(self.notebook_1_pane_3, -1, "Refresh")
        self.sync_time_btn = wx.Button(self.notebook_1_pane_3, -1, "Sync Now")
        self.label_7 = wx.StaticText(self.notebook_1_pane_3, -1, "Calibrate Servo:")
        self.label_8 = wx.StaticText(self.notebook_1_pane_3, -1, "Min Temp.")
        self.min_temp = wx.SpinCtrl(self.notebook_1_pane_3, -1, "", min=0, max=100)
        self.label_12 = wx.StaticText(self.notebook_1_pane_3, -1, "Min Angle")
        self.min_angle = wx.Slider(self.notebook_1_pane_3, -1, 0, 0, 10)
        self.label_9 = wx.StaticText(self.notebook_1_pane_3, -1, "Max Temp.")
        self.max_temp = wx.SpinCtrl(self.notebook_1_pane_3, -1, "", min=0, max=100)
        self.label_12_copy = wx.StaticText(self.notebook_1_pane_3, -1, "Max Angle")
        self.max_angle = wx.Slider(self.notebook_1_pane_3, -1, 0, 0, 10)
        self.label_11 = wx.StaticText(self.notebook_1_pane_3, -1, "Serial Port:")
        self.serial_port = wx.TextCtrl(self.notebook_1_pane_3, -1, "")
        self.button_2 = wx.Button(self.notebook_1_pane_3, -1, "Connect")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_SPINCTRL, self.on_default_temperature_change, self.default_temperature)
        self.Bind(wx.EVT_BUTTON, self.on_help_click, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.on_reset_programme_click, self.reset_changes_btn)
        self.Bind(wx.EVT_BUTTON, self.on_load_programmes_click, self.load_programmes_btn)
        self.Bind(wx.EVT_BUTTON, self.on_refresh_time_click, self.refresh_time_btn)
        self.Bind(wx.EVT_BUTTON, self.on_sync_time_click, self.sync_time_btn)
        self.Bind(wx.EVT_SPINCTRL, self.on_min_temp_change, self.min_temp)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.on_min_angle_change, self.min_angle)
        self.Bind(wx.EVT_SPINCTRL, self.on_max_temp_change, self.max_temp)
        self.Bind(wx.EVT_COMMAND_SCROLL, self.on_max_angle_change, self.max_angle)
        self.Bind(wx.EVT_BUTTON, self.on_connect_click, self.button_2)
        self.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGING, self.on_notebook_change, self.notebook)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainWindow.__set_properties
        self.SetTitle("Thermduino")
        self.SetSize((379, 509))
        self.status.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.temperature.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.device_time_date.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_6.SetFont(wx.Font(10, wx.DEFAULT, wx.ITALIC, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainWindow.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.FlexGridSizer(3, 2, 20, 10)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_3 = wx.FlexGridSizer(3, 2, 5, 5)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(3, 2, 5, 10)
        grid_sizer_1.Add(self.label_1, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.status, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_3, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.default_temperature, 0, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_4, 0, 0, 0)
        grid_sizer_1.Add(self.temperature, 0, wx.EXPAND, 0)
        grid_sizer_1.AddGrowableCol(1)
        sizer_9.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_9.Add(self.bitmap_1, 0, wx.BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_9.Add((20, 30), 0, wx.EXPAND, 0)
        sizer_9.Add((20, 0), 0, 0, 0)
        self.notebook_1_pane_1.SetSizer(sizer_9)
        sizer_2.Add(self.programme_editor, 1, wx.EXPAND, 0)
        sizer_3.Add(self.button_3, 0, 0, 0)
        sizer_3.Add((2, 2), 1, wx.EXPAND, 0)
        sizer_3.Add(self.reset_changes_btn, 0, 0, 0)
        sizer_3.Add(self.load_programmes_btn, 0, 0, 0)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        self.notebook_1_pane_2.SetSizer(sizer_2)
        grid_sizer_2.Add(self.label_5, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_4.Add(self.device_time_date, 0, 0, 0)
        sizer_4.Add(self.label_6, 0, 0, 0)
        sizer_5.Add(self.refresh_time_btn, 0, 0, 0)
        sizer_5.Add(self.sync_time_btn, 0, 0, 0)
        sizer_4.Add(sizer_5, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_7, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_8, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.min_temp, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_12, 0, 0, 0)
        grid_sizer_3.Add(self.min_angle, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_9, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.max_temp, 0, wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_12_copy, 0, 0, 0)
        grid_sizer_3.Add(self.max_angle, 0, wx.EXPAND, 0)
        grid_sizer_3.AddGrowableCol(1)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_11, 0, 0, 0)
        sizer_8.Add(self.serial_port, 1, wx.EXPAND, 0)
        sizer_8.Add(self.button_2, 0, 0, 0)
        grid_sizer_2.Add(sizer_8, 1, wx.EXPAND, 0)
        self.notebook_1_pane_3.SetSizer(grid_sizer_2)
        grid_sizer_2.AddGrowableCol(1)
        self.notebook.AddPage(self.notebook_1_pane_1, "Dashboard")
        self.notebook.AddPage(self.notebook_1_pane_2, "Programmes")
        self.notebook.AddPage(self.notebook_1_pane_3, "Setup")
        sizer_1.Add(self.notebook, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def on_default_temperature_change(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_default_temperature_change' not implemented!"
        event.Skip()

    def on_help_click(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_help_click' not implemented!"
        event.Skip()

    def on_reset_programme_click(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_reset_programme_click' not implemented!"
        event.Skip()

    def on_load_programmes_click(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_load_programmes_click' not implemented!"
        event.Skip()

    def on_refresh_time_click(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_refresh_time_click' not implemented!"
        event.Skip()

    def on_sync_time_click(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_sync_time_click' not implemented!"
        event.Skip()

    def on_min_temp_change(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_min_temp_change' not implemented!"
        event.Skip()

    def on_min_angle_change(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_min_angle_change' not implemented!"
        event.Skip()

    def on_max_temp_change(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_max_temp_change' not implemented!"
        event.Skip()

    def on_max_angle_change(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_max_angle_change' not implemented!"
        event.Skip()

    def on_connect_click(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_connect_click' not implemented!"
        event.Skip()

    def on_notebook_change(self, event): # wxGlade: MainWindow.<event_handler>
        print "Event handler `on_notebook_change' not implemented!"
        event.Skip()

# end of class MainWindow


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    Thermduino = MainWindow(None, -1, "")
    app.SetTopWindow(Thermduino)
    Thermduino.Show()
    app.MainLoop()
